{
 "title": "OSC / DP-Service - test",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(dpdk_heap_info,cluster)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(dpdk_heap_info{cluster=~\"$cluster\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "DP-Service Heap Size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "dpdk_heap_info{info=\"Heap_size\", cluster=~\"$cluster\", pod=~\"$pod\"}",
     "legendFormat": "{{cluster}} {{pod}}"
    }
   ]
  },
  {
   "title": "DP-Service Free Size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "dpdk_heap_info{info=\"Free_size\", cluster=~\"$cluster\", pod=~\"$pod\"}",
     "legendFormat": "{{cluster}} {{pod}}"
    }
   ]
  },
  {
   "title": "DP-Service Alloc Size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "dpdk_heap_info{info=\"Alloc_size\", cluster=~\"$cluster\", pod=~\"$pod\"}",
     "legendFormat": "{{cluster}} {{pod}}"
    }
   ]
  },
  {
   "title": "DP-Service Greatest Free Size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "dpdk_heap_info{info=\"Greatest_free_size\", cluster=~\"$cluster\", pod=~\"$pod\"}",
     "legendFormat": "{{cluster}} {{pod}}"
    }
   ]
  },
  {
   "title": "DP-Service Alloc Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "dpdk_heap_info{info=\"Alloc_count\", cluster=~\"$cluster\", pod=~\"$pod\"}",
     "legendFormat": "{{cluster}} {{pod}}"
    }
   ]
  },
  {
   "title": "DP-Service Free Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "dpdk_heap_info{info=\"Free_count\", cluster=~\"$cluster\", pod=~\"$pod\"}",
     "legendFormat": "{{cluster}} {{pod}}"
    }
   ]
  },
  {
   "title": "DP-Service NAT Used Ports",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sort(dpdk_interface_stat{stat_name=\"nat_used_port_count\", cluster=~\"$cluster\", pod=~\"$pod\"})",
     "legendFormat": "{{cluster}} {{pod}} {{interface}}"
    }
   ]
  },
  {
   "title": "DP-Service VirtualService Used NAT Ports",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "dpdk_interface_stat{stat_name=\"virtsvc_used_port_count\", cluster=~\"$cluster\", pod=~\"$pod\"}",
     "legendFormat": "{{cluster}} {{pod}} {{interface}}"
    }
   ]
  }
 ]
}